[package]
name = "highground"
version = "0.1.0"
edition = "2018"

[dependencies]
macroquad = "0.3"
glam = {version = "*", features = ["serde"]}
serde = {version = "1.0", features = ["derive"]}
bincode = "1.0"
futures = "*"